-- MySQL Script generated by MySQL Workbench
-- 06/22/18 14:14:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AGENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AGENCIA` (
  `cod_A` INT NOT NULL,
  PRIMARY KEY (`cod_A`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Realiza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Realiza` (
  `Reserva_codigoR` INT NOT NULL,
  `Cliente_Cod_cli` INT NOT NULL,
  `Cliente_Cod_cli1` INT NOT NULL,
  INDEX `fk_Realiza_Reserva1_idx` (`Reserva_codigoR` ASC),
  PRIMARY KEY (`Cliente_Cod_cli`, `Cliente_Cod_cli1`),
  CONSTRAINT `fk_Realiza_Reserva1`
    FOREIGN KEY (`Reserva_codigoR`)
    REFERENCES `mydb`.`Reserva` (`codigoR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Realiza_Cliente1`
    FOREIGN KEY (`Cliente_Cod_cli`)
    REFERENCES `mydb`.`Cliente` (`Cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `codigoR` INT NOT NULL,
  `indicador` VARCHAR(15) NULL,
  `F_I` DATE NULL,
  `F_F` DATE NULL,
  `Litro` FLOAT NULL,
  `Realiza_AGENCIA_cod_A` INT NOT NULL,
  PRIMARY KEY (`codigoR`),
  INDEX `fk_Reserva_Realiza1_idx` (`Realiza_AGENCIA_cod_A` ASC),
  CONSTRAINT `fk_Reserva_Realiza1`
    FOREIGN KEY (`Realiza_AGENCIA_cod_A`)
    REFERENCES `mydb`.`Realiza` (`AGENCIA_cod_A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Cod_cli` INT NOT NULL,
  `Tf` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `DNI` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Realiza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Realiza` (
  `Reserva_codigoR` INT NOT NULL,
  `Cliente_Cod_cli` INT NOT NULL,
  `Cliente_Cod_cli1` INT NOT NULL,
  INDEX `fk_Realiza_Reserva1_idx` (`Reserva_codigoR` ASC),
  PRIMARY KEY (`Cliente_Cod_cli`, `Cliente_Cod_cli1`),
  CONSTRAINT `fk_Realiza_Reserva1`
    FOREIGN KEY (`Reserva_codigoR`)
    REFERENCES `mydb`.`Reserva` (`codigoR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Realiza_Cliente1`
    FOREIGN KEY (`Cliente_Cod_cli`)
    REFERENCES `mydb`.`Cliente` (`Cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Involucra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Involucra` (
  `P_arquiler` VARCHAR(15) NOT NULL,
  `Reserva_codigoR` INT NOT NULL,
  PRIMARY KEY (`P_arquiler`, `Reserva_codigoR`),
  INDEX `fk_Involucra_Reserva1_idx` (`Reserva_codigoR` ASC),
  CONSTRAINT `fk_Involucra_Reserva1`
    FOREIGN KEY (`Reserva_codigoR`)
    REFERENCES `mydb`.`Reserva` (`codigoR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coche` (
  `Matricula` INT NOT NULL,
  `Marca` VARCHAR(15) NULL,
  `Modelo` VARCHAR(15) NULL,
  `Involucra_P_arquiler` VARCHAR(15) NOT NULL,
  `Involucra_Reserva_codigoR` INT NOT NULL,
  PRIMARY KEY (`Matricula`, `Involucra_P_arquiler`, `Involucra_Reserva_codigoR`),
  INDEX `fk_Coche_Involucra1_idx` (`Involucra_P_arquiler` ASC, `Involucra_Reserva_codigoR` ASC),
  CONSTRAINT `fk_Coche_Involucra1`
    FOREIGN KEY (`Involucra_P_arquiler` , `Involucra_Reserva_codigoR`)
    REFERENCES `mydb`.`Involucra` (`P_arquiler` , `Reserva_codigoR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Garaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Garaje` (
  `Cod_G` INT NOT NULL,
  PRIMARY KEY (`Cod_G`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asigna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asigna` (
  `Garaje_Cod_G` INT NOT NULL,
  `Coche_Matricula` INT NOT NULL,
  INDEX `fk_Asigna_Garaje_idx` (`Garaje_Cod_G` ASC),
  PRIMARY KEY (`Coche_Matricula`),
  CONSTRAINT `fk_Asigna_Garaje`
    FOREIGN KEY (`Garaje_Cod_G`)
    REFERENCES `mydb`.`Garaje` (`Cod_G`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asigna_Coche1`
    FOREIGN KEY (`Coche_Matricula`)
    REFERENCES `mydb`.`Coche` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avala` (
  `Cliente_Cod_cli` INT NOT NULL,
  `Cliente_Cod_cli1` INT NOT NULL,
  `Cliente_Cod_cli2` INT NOT NULL,
  `Cliente_Cod_cli3` INT NOT NULL,
  INDEX `fk_Avala_Cliente1_idx` (`Cliente_Cod_cli` ASC, `Cliente_Cod_cli1` ASC),
  INDEX `fk_Avala_Cliente2_idx` (`Cliente_Cod_cli2` ASC, `Cliente_Cod_cli3` ASC),
  CONSTRAINT `fk_Avala_Cliente1`
    FOREIGN KEY (`Cliente_Cod_cli`)
    REFERENCES `mydb`.`Cliente` (`Cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avala_Cliente2`
    FOREIGN KEY (`Cliente_Cod_cli2`)
    REFERENCES `mydb`.`Cliente` (`Cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
