-- MySQL Script generated by MySQL Workbench
-- 06/22/18 14:02:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema phpmyadmin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phpmyadmin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phpmyadmin` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema renta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renta` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema renta_carros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renta_carros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renta_carros` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Cod_cli` INT NOT NULL,
  `Tf` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Cod_cli` INT NOT NULL,
  PRIMARY KEY (`Cod_cli`, `Cod_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Realiza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Realiza` (
  `Cliente_Cod_cli` INT NOT NULL,
  `Cliente_Cod_cli1` INT NOT NULL,
  PRIMARY KEY (`Cliente_Cod_cli`, `Cliente_Cod_cli1`),
  CONSTRAINT `fk_Realiza_Cliente1`
    FOREIGN KEY (`Cliente_Cod_cli` , `Cliente_Cod_cli1`)
    REFERENCES `mydb`.`Cliente` (`Cod_cli` , `Cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AGENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AGENCIA` (
  `cod_A` INT NOT NULL,
  PRIMARY KEY (`cod_A`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Realiza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Realiza` (
  `Cliente_Cod_cli` INT NOT NULL,
  `Cliente_Cod_cli1` INT NOT NULL,
  PRIMARY KEY (`Cliente_Cod_cli`, `Cliente_Cod_cli1`),
  CONSTRAINT `fk_Realiza_Cliente1`
    FOREIGN KEY (`Cliente_Cod_cli` , `Cliente_Cod_cli1`)
    REFERENCES `mydb`.`Cliente` (`Cod_cli` , `Cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `codigoR` INT NOT NULL,
  `indicador` VARCHAR(15) NULL,
  `F_I` VARCHAR(15) NULL,
  `F_F` VARCHAR(15) NULL,
  `Litro` FLOAT NULL,
  `Realiza_Cliente_Cod_cli` INT NOT NULL,
  `Realiza_Cliente_Cod_cli1` INT NOT NULL,
  `Realiza_AGENCIA_cod_A` INT NOT NULL,
  PRIMARY KEY (`codigoR`, `Realiza_Cliente_Cod_cli`, `Realiza_Cliente_Cod_cli1`, `Realiza_AGENCIA_cod_A`),
  INDEX `fk_Reserva_Realiza1_idx` (`Realiza_Cliente_Cod_cli` ASC, `Realiza_Cliente_Cod_cli1` ASC),
  INDEX `fk_Reserva_Realiza2_idx` (`Realiza_AGENCIA_cod_A` ASC),
  CONSTRAINT `fk_Reserva_Realiza1`
    FOREIGN KEY (`Realiza_Cliente_Cod_cli` , `Realiza_Cliente_Cod_cli1`)
    REFERENCES `mydb`.`Realiza` (`Cliente_Cod_cli` , `Cliente_Cod_cli1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Realiza2`
    FOREIGN KEY (`Realiza_AGENCIA_cod_A`)
    REFERENCES `mydb`.`Realiza` (`AGENCIA_cod_A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Involucra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Involucra` (
  `P_arquiler` VARCHAR(15) NOT NULL,
  `Reserva_codigoR` INT NOT NULL,
  `Reserva_codigoR1` INT NOT NULL,
  `Reserva_Realiza_Cliente_Cod_cli` INT NOT NULL,
  `Reserva_Realiza_Cliente_Cod_cli1` INT NOT NULL,
  `Reserva_Realiza_AGENCIA_cod_A` INT NOT NULL,
  PRIMARY KEY (`P_arquiler`, `Reserva_codigoR`, `Reserva_codigoR1`, `Reserva_Realiza_Cliente_Cod_cli`, `Reserva_Realiza_Cliente_Cod_cli1`, `Reserva_Realiza_AGENCIA_cod_A`),
  INDEX `fk_Involucra_Reserva1_idx` (`Reserva_codigoR1` ASC, `Reserva_Realiza_Cliente_Cod_cli` ASC, `Reserva_Realiza_Cliente_Cod_cli1` ASC, `Reserva_Realiza_AGENCIA_cod_A` ASC),
  CONSTRAINT `fk_Involucra_Reserva1`
    FOREIGN KEY (`Reserva_codigoR1` , `Reserva_Realiza_Cliente_Cod_cli` , `Reserva_Realiza_Cliente_Cod_cli1` , `Reserva_Realiza_AGENCIA_cod_A`)
    REFERENCES `mydb`.`Reserva` (`codigoR` , `Realiza_Cliente_Cod_cli` , `Realiza_Cliente_Cod_cli1` , `Realiza_AGENCIA_cod_A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asigna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asigna` (
  `Coche_Matricula` INT NOT NULL,
  PRIMARY KEY (`Coche_Matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coche` (
  `Matricula` INT NOT NULL,
  `Marca` VARCHAR(15) NULL,
  `Modelo` VARCHAR(15) NULL,
  `Involucra_P_arquiler` VARCHAR(15) NOT NULL,
  `Involucra_Reserva_codigoR` INT NOT NULL,
  `Asigna_Coche_Matricula` INT NOT NULL,
  PRIMARY KEY (`Matricula`, `Involucra_P_arquiler`, `Involucra_Reserva_codigoR`, `Asigna_Coche_Matricula`),
  INDEX `fk_Coche_Involucra1_idx` (`Involucra_P_arquiler` ASC, `Involucra_Reserva_codigoR` ASC),
  INDEX `fk_Coche_Asigna1_idx` (`Asigna_Coche_Matricula` ASC),
  CONSTRAINT `fk_Coche_Involucra1`
    FOREIGN KEY (`Involucra_P_arquiler` , `Involucra_Reserva_codigoR`)
    REFERENCES `mydb`.`Involucra` (`P_arquiler` , `Reserva_codigoR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coche_Asigna1`
    FOREIGN KEY (`Asigna_Coche_Matricula`)
    REFERENCES `mydb`.`Asigna` (`Coche_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Garaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Garaje` (
  `Cod_G` INT NOT NULL,
  `Asigna_Coche_Matricula` INT NOT NULL,
  PRIMARY KEY (`Cod_G`, `Asigna_Coche_Matricula`),
  INDEX `fk_Garaje_Asigna1_idx` (`Asigna_Coche_Matricula` ASC),
  CONSTRAINT `fk_Garaje_Asigna1`
    FOREIGN KEY (`Asigna_Coche_Matricula`)
    REFERENCES `mydb`.`Asigna` (`Coche_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avala` (
  `Cliente_Cod_cli` INT NOT NULL,
  `Cliente_Cod_cli1` INT NOT NULL,
  `Cliente_Cod_cli2` INT NOT NULL,
  `Cliente_Cod_cli3` INT NOT NULL,
  INDEX `fk_Avala_Cliente1_idx` (`Cliente_Cod_cli` ASC, `Cliente_Cod_cli1` ASC),
  INDEX `fk_Avala_Cliente2_idx` (`Cliente_Cod_cli2` ASC, `Cliente_Cod_cli3` ASC),
  CONSTRAINT `fk_Avala_Cliente1`
    FOREIGN KEY (`Cliente_Cod_cli` , `Cliente_Cod_cli1`)
    REFERENCES `mydb`.`Cliente` (`Cod_cli` , `Cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avala_Cliente2`
    FOREIGN KEY (`Cliente_Cod_cli2` , `Cliente_Cod_cli3`)
    REFERENCES `mydb`.`Cliente` (`Cod_cli` , `Cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `phpmyadmin` ;

-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__bookmark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__bookmark` (
  `id` INT(11) NOT NULL,
  `dbase` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `user` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `label` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `query` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Bookmarks';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__central_columns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__central_columns` (
  `db_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `col_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `col_type` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `col_length` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `col_collation` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `col_isNull` TINYINT(1) NOT NULL,
  `col_extra` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT '',
  `col_default` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`db_name`, `col_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Central list of columns';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__column_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__column_info` (
  `id` INT(5) UNSIGNED NOT NULL,
  `db_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `table_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `column_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `comment` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `mimetype` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `transformation` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `transformation_options` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `input_transformation` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `input_transformation_options` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `db_name` (`db_name` ASC, `table_name` ASC, `column_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Column information for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__designer_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__designer_settings` (
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `settings_data` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Settings related to Designer';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__export_templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__export_templates` (
  `id` INT(5) UNSIGNED NOT NULL,
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `export_type` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `template_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `template_data` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_user_type_template` (`username` ASC, `export_type` ASC, `template_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Saved export templates';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__favorite` (
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `tables` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Favorite tables';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__history` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `db` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `table` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `timevalue` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sqlquery` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `username` (`username` ASC, `db` ASC, `table` ASC, `timevalue` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'SQL history for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__navigationhiding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__navigationhiding` (
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `item_type` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `db_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `table_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`username`, `item_name`, `item_type`, `db_name`, `table_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Hidden items of navigation tree';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__pdf_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__pdf_pages` (
  `db_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `page_nr` INT(10) UNSIGNED NOT NULL,
  `page_descr` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  PRIMARY KEY (`page_nr`),
  INDEX `db_name` (`db_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'PDF relation pages for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__recent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__recent` (
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `tables` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Recently accessed tables';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__relation` (
  `master_db` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `master_table` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `master_field` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `foreign_db` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `foreign_table` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `foreign_field` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  PRIMARY KEY (`master_db`, `master_table`, `master_field`),
  INDEX `foreign_field` (`foreign_db` ASC, `foreign_table` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Relation table';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__savedsearches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__savedsearches` (
  `id` INT(5) UNSIGNED NOT NULL,
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `db_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `search_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `search_data` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_savedsearches_username_dbname` (`username` ASC, `db_name` ASC, `search_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Saved searches';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__table_coords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__table_coords` (
  `db_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `table_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `pdf_page_number` INT(11) NOT NULL DEFAULT '0',
  `x` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `y` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`db_name`, `table_name`, `pdf_page_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Table coordinates for phpMyAdmin PDF output';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__table_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__table_info` (
  `db_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `table_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `display_field` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  PRIMARY KEY (`db_name`, `table_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Table information for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__table_uiprefs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__table_uiprefs` (
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `db_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `table_name` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `prefs` TEXT CHARACTER SET 'utf8' NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Tables\' UI preferences';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__userconfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__userconfig` (
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `timevalue` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `config_data` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'User preferences storage for phpMyAdmin';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__usergroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__usergroups` (
  `usergroup` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `tab` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `allowed` ENUM('Y', 'N') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  PRIMARY KEY (`usergroup`, `tab`, `allowed`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'User groups with configured menu items';


-- -----------------------------------------------------
-- Table `phpmyadmin`.`pma__users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpmyadmin`.`pma__users` (
  `username` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  `usergroup` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`username`, `usergroup`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Users and their assignments to user groups';

USE `renta` ;

-- -----------------------------------------------------
-- Table `renta`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta`.`agencia` (
  `Cod_A` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Cod_A`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `renta`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta`.`cliente` (
  `cod_cli` VARCHAR(10) NOT NULL,
  `Direccion` TINYTEXT NULL DEFAULT NULL,
  `Tf` INT(10) NULL DEFAULT NULL,
  `DNI` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_cli`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `renta`.`coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta`.`coche` (
  `Matricula` VARCHAR(10) NOT NULL,
  `Marca` TINYTEXT NULL DEFAULT NULL,
  `Modelo` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `renta`.`garage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta`.`garage` (
  `Cod_G` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Cod_G`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `renta`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta`.`reserva` (
  `Cod_R` VARCHAR(10) NOT NULL,
  `F_ÿÿÿÿÿÿ0Zæ4I` DATE NULL DEFAULT NULL,
  `F_F` DATE NULL DEFAULT NULL,
  `Litro` INT(10) NULL DEFAULT NULL,
  `Precio_T` INT(10) NULL DEFAULT NULL,
  `Indicador` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_R`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `renta`.`involucra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta`.`involucra` (
  `Cod_R` VARCHAR(10) NULL DEFAULT NULL,
  `Matricula` VARCHAR(10) NULL DEFAULT NULL,
  `P_Alquiler` INT(10) NULL DEFAULT NULL,
  INDEX `Cod_R` (`Cod_R` ASC),
  INDEX `Matricula` (`Matricula` ASC),
  CONSTRAINT `involucra_ibfk_1`
    FOREIGN KEY (`Cod_R`)
    REFERENCES `renta`.`reserva` (`Cod_R`),
  CONSTRAINT `involucra_ibfk_2`
    FOREIGN KEY (`Matricula`)
    REFERENCES `renta`.`coche` (`Matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `renta_carros` ;

-- -----------------------------------------------------
-- Table `renta_carros`.`renta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `renta_carros`.`renta` (
  `Coche` VARCHAR(20) NOT NULL,
  `Agencia` VARCHAR(20) NOT NULL,
  `Garage` INT(15) NOT NULL,
  `Reserva` INT(15) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`coche` (
  `Matricula` VARCHAR(10) NOT NULL,
  `Marca` TINYTEXT NULL DEFAULT NULL,
  `Modelo` TINYTEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `test`.`garage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`garage` (
  `Cod_G` VARCHAR(10) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `test`.`involucra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`involucra` (
  `Cod_R` VARCHAR(10) NULL DEFAULT NULL,
  `Matricula` VARCHAR(10) NULL DEFAULT NULL,
  `P_Alquiler` INT(10) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
